model: bert

framework: tensorflow

workflow:
  generate_data: False
  train: True
  debug: False
  checkpoint: True
  profiling: False
  evaluation: True
 
dataset: 
  data_folder: data/bert
  format: tfrecord
  num_files_train: 500
  num_files_eval: 1
  num_samples_per_file: 313532
  record_length: 2500
  interleave: True

train:
  total_training_steps: 2400

evaluation:
  eval_time: 0.968
  eval_after_epoch: 1
  total_eval_steps: 100
 
reader:
  data_loader: tensorflow
  read_threads: 8
  computation_threads: 8
  transfer_size: 262144
  batch_size: 6
  batch_size_eval: 1
  file_shuffle: seed
  sample_shuffle: seed

checkpoint:
  checkpoint_folder: checkpoints/bert
  steps_between_checkpoints: 2400
  checkpoint_after_step: 0
  model_size: 4034713312
  