model: cosmoflow

framework: tensorflow

workflow:
 generate_data: True
 train: True

dataset:
 data_folder: ./data/cosmoflow
 num_files_train: 1024
 num_samples_per_file: 512
 record_length: 131072
 batch_size: 1

data_reader:
 data_loader: tensorflow
 computation_threads: 8
 read_threads: 8

train: 
  epochs: 4
