model: unet3d

framework: pytorch

workflow:
  generate_data: False
  train: True
  checkpoint: True
  evaluation: True
  profiling: False

dataset: 
  data_folder: data/unet3d/
  format: npy
  num_files_train: 168
  num_files_eval: 42
  num_samples_per_file: 1
  record_length: 234560851
  record_length_stdev: 109346892
  
reader: 
  data_loader: pytorch
  batch_size: 4
  batch_size_eval: 1
  read_threads: 1
  file_shuffle: seed
  sample_shuffle: seed

train:
  epochs: 50

evaluation: 
  eval_time: 8.9027
  eval_time_stdev: 3.9049
  eval_after_epoch: 25
  epochs_between_evals: 25

checkpoint:
  checkpoint_folder: checkpoints/unet3d
  checkpoint_after_epoch: 50
  model_size: 499153191
  ckpt_write_sz_q1: 1280
  ckpt_write_sz_mean: 2170231
  ckpt_write_sz_std: 4459727
  ckpt_write_sz_min: 64
