model: unet3d

framework: pytorch

workflow:
  generate_data: False
  train: True
  evaluation: True

dataset: 
  data_folder: ./data/unet3d/
  format: npz
  num_files_train: 3620
  num_files_eval: 42
  num_samples_per_file: 1
  batch_size: 4
  batch_size_eval: 1
  file_access: multi
  record_length: 147000000
  keep_files: True
  
data_reader: 
  data_loader: pytorch

train:
  epochs: 10
  computation_time: 4.59

evaluation: 
  eval_time: 11.572
  epochs_between_evals: 2
