name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.5
    - name: Install DLIO
      run: |
        sudo apt-get install mpich
        python -m pip install --upgrade pip
        pip install tensorflow torch h5py mpi4py pandas
        HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 pip install horovod 
        pip install -r requirements.txt
        python setup.py build
        python setup.py install
    - name: test-tf-loader-tfrecord
      run: |
        touch __init__.py
        export PYTHONPATH=./:$PYTHONPATH
        mpirun -n 2 python ./src/dlio_benchmark.py workload=resnet50 ++workload.dataset.num_files_train=64
    - name: test-torch-loader-npz
      run: |
        touch __init__.py
        export PYTHONPATH=./:$PYTHONPATH
        mpirun -n 2 python ./src/dlio_benchmark.py workload=unet3d ++workload.train.computation_time=0.05 ++workload.evaluation.eval_time=0.01 ++workload.train.epochs=2
    - name: test-tf-loader-npz
      run: |
        touch __init__.py
        export PYTHONPATH=./:$PYTHONPATH
        mpirun -n 2 python ./src/dlio_benchmark.py workload=unet3d ++workload.framework=tensorflow ++workload.data_reader.data_loader=tensorflow ++workload.train.computation_time=0.05 ++workload.evaluation.eval_time=0.01 ++workload.train.epochs=2