name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.5
    - name: Install DLIO
      run: |
        sudo apt-get install mpich
        python -m pip install --upgrade pip
        pip install tensorflow h5py mpi4py pandas
        HOROVOD_WITH_TENSORFLOW=1 pip install horovod 
        python setup.py build
        python setup.py install
    - name: test-tf-loader-tfrecord
      run: |
        mkdir -p ResNet50
        touch __init__.py
        export PYTHONPATH=./:$PYTHONPATH
        mpirun -n 2 python ./src/dlio_benchmark.py --config-name resnet50 ++dataset.num_files_train=64 ++dataset.data_folder=ResNet50
    - name: test-torch-loader-npz
      run: |
        mkdir -p UNET3D
        touch __init__.py
        export PYTHONPATH=./:$PYTHONPATH
        mpirun -n 2 python ./src/dlio_benchmark.py --config-name unet3d ++dataset.data_folder=UNET3D
    - name: test-tf-loader-npz
      run: |
        mkdir -p UNET3D
        touch __init__.py
        export PYTHONPATH=./:$PYTHONPATH
        mpirun -n 2 python ./src/dlio_benchmark.py --config-name unet3d ++dataset.data_folder=UNET3D ++framework=tensorflow ++data_loader.data_loader=tensorflow